<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Поиск");
?>
<div class="container">

	<div class="page-content">
		

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.search", 
	"search", 
	array(
		"AJAX_MODE" => "N",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "10",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"DISPLAY_COMPARE" => "N",
		"PAGE_ELEMENT_COUNT" => "30",
		"LINE_ELEMENT_COUNT" => "1",
		"PROPERTY_CODE" => array(
			0 => "CAS",
			1 => "MDL",
			2 => "EINECS",
			3 => "PUB",
			4 => "PRODUCT_ID",
			5 => "FORMULA",
			6 => "FORMA",
			7 => "CLEAN",
			8 => "PACKING_GROUP",
			9 => "INFO_TITLE",
			10 => "IDS",
			11 => "INFO",
			12 => "HAZARD_CLASS",
			13 => "HAZARD_CHAR",
			14 => "SAFETY",
			15 => "MASS",
			16 => "HIDE_IN_TABLE",
			17 => "UN_NUM",
			18 => "SYMBOL",
			19 => "SPECIAL_PROP",
			20 => "PICTOGRAPH",
			21 => "DENSITY",
			22 => "SUBTITLE",
			23 => "NUMBER",
			24 => "HAZARD_WAR",
			25 => "USEING",
			26 => "RASTVOR",
			27 => "OTHERS_NAMES",
			28 => "TAGS",
			29 => "TEMPERATURE_KP",
			30 => "TEMPERATURE_PL",
			31 => "PACKING",
			32 => "COLOR",
			33 => "",
		),
		"OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "NUM",
			1 => "PACKING",
			2 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFERS_LIMIT" => "5",
		"PRICE_CODE" => array(
			0 => "base",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"RESTART" => "N",
		"NO_WORD_LOGIC" => "Y",
		"USE_LANGUAGE_GUESS" => "Y",
		"CHECK_DATES" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_TEMPLATE" => "articles",
		"PAGER_DESC_NUMBERING" => "Y",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"HIDE_NOT_AVAILABLE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => "RUB",
		"OFFERS_CART_PROPERTIES" => array(
		),
		"AJAX_OPTION_JUMP" => "Y",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "Y",
		"COMPONENT_TEMPLATE" => "search",
		"HIDE_NOT_AVAILABLE_OFFERS" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"USE_TITLE_RANK" => "Y",
		"USE_SEARCH_RESULT_ORDER" => "Y"
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>